In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# left to right
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# top to bottom
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [7]:
# a dataframe with NaN if the index is miss for ecah dataset
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [8]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [10]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [11]:
dframe1

X         Y         Z
0 -0.789776 -1.198968  0.280165
1  0.400254  0.864818  0.473788
2  0.507528  0.976628  0.786493
3  0.585097 -0.908462  1.379696

In [12]:
dframe2

Y         Q         X
0  1.618354 -0.814222  0.557216
1  0.960456  0.829783 -0.481177
2 -0.827674 -1.253642 -1.841203

In [13]:
# ignore_index: will reindex the index number influently
pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.789776 -1.198968  0.280165
1       NaN  0.400254  0.864818  0.473788
2       NaN  0.507528  0.976628  0.786493
3       NaN  0.585097 -0.908462  1.379696
4 -0.814222  0.557216  1.618354       NaN
5  0.829783 -0.481177  0.960456       NaN
6 -1.253642 -1.841203 -0.827674       NaN