In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# Get square root of the array
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
# Get exponential value
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
# Get normal distribution of array (specified with random values)
A = np.random.randn(10)
A

array([ 0.95640598, -1.81950847,  0.11799905, -0.41065356, -1.27743291,
        0.06596844,  0.312803  ,  0.29749609, -0.28647827,  0.82875718])

In [9]:
B = np.random.randn(10)
B

array([-0.76176938,  0.66726498,  0.17553208,  0.90427518,  0.85736798,
       -0.44459625,  0.39287342, -0.09762553,  1.34839618, -0.47140768])

In [10]:
# Demo - Basic manipulate
np.add(A,B)

array([ 0.19463661, -1.15224349,  0.29353114,  0.49362162, -0.42006493,
       -0.37862781,  0.70567642,  0.19987056,  1.06191791,  0.3573495 ])

In [12]:
np.maximum(A,B)

array([ 0.95640598,  0.66726498,  0.17553208,  0.90427518,  0.85736798,
        0.06596844,  0.39287342,  0.29749609,  1.34839618,  0.82875718])

In [13]:
# more reference:
# website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
# import webbrowser
# webbrowser.open(website)