In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
# save the array to a numpy file
np.save('my_array', arr)

In [5]:
# load the array file
''' ** must use the .npy extension ** '''
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [8]:
'''
Save multiple arrays to a zip file
The file extension: .npz
'''
arr2 = np.arange(10)
np.savez('zip_array.npz', x = arr, y = arr2)

In [9]:
archive_arr = np.load('zip_array.npz')
archive_arr['x']

array([0, 1, 2, 3, 4])

In [11]:
archive_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
''' Save as a text file: np.savetxt() '''
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('text_array.txt', arr, delimiter = ',')

In [14]:
''' Load in text file: np.loadtxt()
** Default data type is float **
'''
np.loadtxt('text_array.txt', delimiter = ',', dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])