In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
dframe = DataFrame(np.arange(16).reshape(4,4))
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [3]:
blender = np.random.permutation(4)
blender

array([3, 1, 2, 0])

# Use .take() to create permutation!

In [4]:
# Use the row index order by the value of blender
dframe.take(blender)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11
0   0   1   2   3

## Do permutation with replacement

In [5]:
box = np.array([1,2,3])
# Shaker is the set of random index locations of box
shaker = np.random.randint(1,len(box), size=10)
shaker

array([2, 1, 2, 2, 1, 1, 1, 2, 1, 1])

In [7]:
# Get the values from box using the random index in shaker
hand_grabs = box.take(shaker)
hand_grabs

array([3, 2, 3, 3, 2, 2, 2, 3, 2, 2])